"""!
@file pede_job.py

Run pede alignment over input bin files generated by tracking accumulation
"""
import os
from hpsmc.tools import PEDE

job.description = 'alignment parameter minimizatin via pede'

## Run the job
job.add( PEDE() )
