"""!
@file pede_job.py

Run pede alignment over input bin files generated by tracking accumulation
"""
import os
from hpsmc.alignment import PEDE, ApplyPedeRes, ConstructDetector

job.description = 'alignment parameter minimizatin via pede'

pede = PEDE(inputs = job.input_files.values())
apply_res = ApplyPedeRes()
construct_det = ConstructDetector()

job.add([ pede, apply_res, construct_det ])
