c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  1,  5/          !  ELMASS  ZERO    
      data tprid(  -1,   1) /      11/
      data(iforest(i, -2,   1),i=1,2) / -1,  3/          !  ZERO    AWIDTH  
      data tprid(  -2,   1) /      22/
      data(iforest(i, -3,   1),i=1,2) / -2,  4/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  5,  3/          !  ELMASS  ZERO    
      data sprop(  -1,   2) /      11/
      data(iforest(i, -2,   2),i=1,2) /  1, -1/          !  ZERO    AWIDTH  
      data tprid(  -2,   2) /      22/
      data(iforest(i, -3,   2),i=1,2) / -2,  4/          !  
      data mapconfig(   0) /   2/
