ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of idm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_87 = ', GC_87
