#!/bin/bash
#PBS -q madgraph            
#PBS -o /dev/null
#PBS -e /dev/null
if [[ "$PBS_O_WORKDIR" != "" ]]; then
    cd $PBS_O_WORKDIR
fi
k=run1_app.log
script=ajob1                         
rm -f wait.$script >& /dev/null
touch run.$script
j=G1
     echo $j
     if [[ ! -e $j ]]; then
          mkdir $j
     fi
     cd $j
     rm -f $k
     if  [[ -e ftn26 ]]; then
          cp ftn26 ftn25
     fi
     if [[ ! -e ftn25 ]]; then
         echo "    3000       6" >& input_sg.txt
         echo " -12000.000" >> input_sg.txt
         echo "2" >> input_sg.txt
         echo "1" >> input_sg.txt
         echo "   1 " >> input_sg.txt
         echo "1" >>input_sg.txt
          time ../madevent >> $k <input_sg.txt
          cat $k >> log.txt
          if [[ -e ftn26 ]]; then
               cp ftn26 ftn25
          fi
     else
          rm -f $k
         echo "    3000       6" >& input_sg.txt
         echo " -12000.000" >> input_sg.txt
         echo "0" >> input_sg.txt
         echo "1" >> input_sg.txt
         echo "   1 " >> input_sg.txt
         echo "1" >>input_sg.txt
          if [[ -e ftn26 ]]; then
               cp ftn26 ftn25
          fi
          time ../madevent >> $k <input_sg.txt
          cat $k >> log.txt
     fi
     cd ../
rm -f run.$script
touch done.$script
