c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  1,  3/          !  ZERO    AWIDTH  
      data tprid(  -1,   1) /      22/
      data(iforest(i, -2,   1),i=1,2) / -1,  6/          !  ELMASS  ELWIDTH 
      data tprid(  -2,   1) /     611/
      data(iforest(i, -3,   1),i=1,2) / -2,  5/          !  ZERO    AWIDTH  
      data tprid(  -3,   1) /      22/
      data(iforest(i, -4,   1),i=1,2) / -3,  4/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  1,  3/          !  ZERO    AWIDTH  
      data tprid(  -1,   2) /      22/
      data(iforest(i, -2,   2),i=1,2) / -1,  5/          !  ELMASS  ELWIDTH 
      data tprid(  -2,   2) /     611/
      data(iforest(i, -3,   2),i=1,2) / -2,  6/          !  ZERO    AWIDTH  
      data tprid(  -3,   2) /      22/
      data(iforest(i, -4,   2),i=1,2) / -3,  4/          !  
      data mapconfig(   0) /   2/
