ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_Ap_Rho_Pi'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_17 = ', GC_17
