#!/bin/bash

#for APM in 0.050 0.100 0.200 0.300 0.400 0.500 0.800; do

for APM in 0.01 0.02 0.03 0.04 0.06 0.08 0.12 0.15 0.18 0.25 0.35 0.45 0.6 0.7; do

APMGEV=`perl -e "printf '%10.8f', $APM"`

# put the right mass in the card file
sed -i.bak "s/.\....00000e-00\(.*\)APMASS/${APMGEV}e-00\1APMASS/"  \
   Cards/param_card.dat

./bin/generate_events 0 AP_6Wff_${APM}_Xsec

done