c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  1,  6/          !  ZERO    AWIDTH  
      data tprid(  -1,   1) /      22/
      data(iforest(i, -2,   1),i=1,2) / -1,  5/          !  ELEMASS ZERO    
      data tprid(  -2,   1) /     -11/
      data(iforest(i, -3,   1),i=1,2) / -2,  3/          !  ZERO    AWIDTH  
      data tprid(  -3,   1) /      22/
      data(iforest(i, -4,   1),i=1,2) / -3,  4/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  5,  3/          !  ZERO    AWIDTH  
      data sprop(  -1,   2) /      22/
      data(iforest(i, -2,   2),i=1,2) /  1, -1/          !  ELEMASS ZERO    
      data tprid(  -2,   2) /      11/
      data(iforest(i, -3,   2),i=1,2) / -2,  6/          !  ZERO    AWIDTH  
      data tprid(  -3,   2) /      22/
      data(iforest(i, -4,   2),i=1,2) / -3,  4/          !  
c   Graph      3
      data mapconfig(   3) /   3/
      data(iforest(i, -1,   3),i=1,2) /  5,  3/          !  ZERO    AWIDTH  
      data sprop(  -1,   3) /      22/
      data(iforest(i, -2,   3),i=1,2) /  6, -1/          !  ELEMASS ZERO    
      data sprop(  -2,   3) /      11/
      data(iforest(i, -3,   3),i=1,2) /  1, -2/          !  ZERO    AWIDTH  
      data tprid(  -3,   3) /      22/
      data(iforest(i, -4,   3),i=1,2) / -3,  4/          !  
c   Graph      4
      data mapconfig(   4) /   4/
      data(iforest(i, -1,   4),i=1,2) /  1,  6/          !  ZERO    AWIDTH  
      data tprid(  -1,   4) /      22/
      data(iforest(i, -2,   4),i=1,2) / -1,  3/          !  ELEMASS ZERO    
      data tprid(  -2,   4) /      11/
      data(iforest(i, -3,   4),i=1,2) / -2,  5/          !  ZERO    AWIDTH  
      data tprid(  -3,   4) /      22/
      data(iforest(i, -4,   4),i=1,2) / -3,  4/          !  
c   Graph      5
      data mapconfig(   5) /   5/
      data(iforest(i, -1,   5),i=1,2) /  6,  5/          !  ZERO    AWIDTH  
      data sprop(  -1,   5) /      22/
      data(iforest(i, -2,   5),i=1,2) /  1, -1/          !  ELEMASS ZERO    
      data tprid(  -2,   5) /     -11/
      data(iforest(i, -3,   5),i=1,2) / -2,  3/          !  ZERO    AWIDTH  
      data tprid(  -3,   5) /      22/
      data(iforest(i, -4,   5),i=1,2) / -3,  4/          !  
c   Graph      6
      data mapconfig(   6) /   6/
      data(iforest(i, -1,   6),i=1,2) /  6,  5/          !  ZERO    AWIDTH  
      data sprop(  -1,   6) /      22/
      data(iforest(i, -2,   6),i=1,2) / -1,  3/          !  ELEMASS ZERO    
      data sprop(  -2,   6) /      11/
      data(iforest(i, -3,   6),i=1,2) /  1, -2/          !  ZERO    AWIDTH  
      data tprid(  -3,   6) /      22/
      data(iforest(i, -4,   6),i=1,2) / -3,  4/          !  
c   Graph      7
      data mapconfig(   7) /   7/
      data(iforest(i, -1,   7),i=1,2) /  1,  3/          !  ZERO    AWIDTH  
      data tprid(  -1,   7) /      22/
      data(iforest(i, -2,   7),i=1,2) / -1,  6/          !  ELEMASS ZERO    
      data tprid(  -2,   7) /      11/
      data(iforest(i, -3,   7),i=1,2) / -2,  5/          !  ZERO    AWIDTH  
      data tprid(  -3,   7) /      22/
      data(iforest(i, -4,   7),i=1,2) / -3,  4/          !  
c   Graph      8
      data mapconfig(   8) /   8/
      data(iforest(i, -1,   8),i=1,2) /  1,  3/          !  ZERO    AWIDTH  
      data tprid(  -1,   8) /      22/
      data(iforest(i, -2,   8),i=1,2) / -1,  5/          !  ELEMASS ZERO    
      data tprid(  -2,   8) /      11/
      data(iforest(i, -3,   8),i=1,2) / -2,  6/          !  ZERO    AWIDTH  
      data tprid(  -3,   8) /      22/
      data(iforest(i, -4,   8),i=1,2) / -3,  4/          !  
      data mapconfig(   0) /   8/
