#!/bin/bash

if [ $# -lt 2 ] ; then
    echo "usage: runMany <numBH> <numRad> <label>"
    exit
fi

imaxBH=$1
label=$2

i=0

cp Cards/run_card.dat ../new_trident_Rad_new_cuts3/Cards/

#for x in 01 02 03 04 05 06 07 08 09 10 ; do
for x in 01 02 03 04 05 06 07 08 09 10 ; do
    if [ $i -lt $imaxBH ]; then
        ./bin/generate_events 0 ${label}_ALL_$x
    fi
    let i="$i+1"
done
