#!/bin/bash

if [ $# -lt 2 ] ; then
    echo "usage: runMany <numSig> <label>"
    exit
fi

imaxSig=$1
label=$2

i=0

for x in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20; do
    if [ $i -lt $imaxSig ]; then
        ./bin/generate_events 0 ${label}_$x
    fi

    let i="$i+1"
done
