C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/1,3/
      DATA TPRID(-1,1)/22/
      DATA (SPROP(I,-1,1),I=1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,5/
      DATA TPRID(-2,1)/11/
      DATA (SPROP(I,-2,1),I=1,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/-2,6/
      DATA TPRID(-3,1)/22/
      DATA (SPROP(I,-3,1),I=1,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/-3,4/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/1,3/
      DATA TPRID(-1,2)/22/
      DATA (SPROP(I,-1,2),I=1,1)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/-1,6/
      DATA TPRID(-2,2)/11/
      DATA (SPROP(I,-2,2),I=1,1)/0/
      DATA (IFOREST(I,-3,2),I=1,2)/-2,5/
      DATA TPRID(-3,2)/22/
      DATA (SPROP(I,-3,2),I=1,1)/0/
      DATA (IFOREST(I,-4,2),I=1,2)/-3,4/
C     Diagram 3
      DATA MAPCONFIG(3)/3/
      DATA (IFOREST(I,-1,3),I=1,2)/1,5/
      DATA TPRID(-1,3)/22/
      DATA (SPROP(I,-1,3),I=1,1)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/-1,3/
      DATA TPRID(-2,3)/11/
      DATA (SPROP(I,-2,3),I=1,1)/0/
      DATA (IFOREST(I,-3,3),I=1,2)/-2,6/
      DATA TPRID(-3,3)/22/
      DATA (SPROP(I,-3,3),I=1,1)/0/
      DATA (IFOREST(I,-4,3),I=1,2)/-3,4/
C     Diagram 4
      DATA MAPCONFIG(4)/4/
      DATA (IFOREST(I,-1,4),I=1,2)/1,5/
      DATA TPRID(-1,4)/22/
      DATA (SPROP(I,-1,4),I=1,1)/0/
      DATA (IFOREST(I,-2,4),I=1,2)/-1,6/
      DATA TPRID(-2,4)/11/
      DATA (SPROP(I,-2,4),I=1,1)/0/
      DATA (IFOREST(I,-3,4),I=1,2)/-2,3/
      DATA TPRID(-3,4)/22/
      DATA (SPROP(I,-3,4),I=1,1)/0/
      DATA (IFOREST(I,-4,4),I=1,2)/-3,4/
C     Number of configs
      DATA MAPCONFIG(0)/4/
