#!/usr/bin/env bash

print_jobs() {
    echo "Available job names:"
    for j in $(ls $HPSMC_DIR/lib/python/jobs/*_job.py); do
        jn=$(basename $j | sed s/_job.py//g)
        echo "  $jn"
    done
}

if [ -z "$HPSMC_DIR" ]; then
    echo "ERROR: The $HPSMC_DIR is not set!"
    exit 1
fi

if [ "$#" -ne 2 ]; then
    echo "Usage: hps-mc-job [job_name] [job_params]"
    print_jobs 
    exit 1
fi

job_name=$1
job_params=$2

echo "job_name=$job_name"
echo "job_params=$job_params"

job_script=$HPSMC_DIR/lib/python/jobs/${job_name}_job.py
echo "job_script=$job_script"

if [ -f "$job_script" ]; then
    python $job_script $job_params
else 
    echo "ERROR: No job script exists for '${job_name}' in '$HPSMC_DIR/lib/python/jobs' dir."
    print_jobs
fi
