#!/bin/bash

if [ $# -lt 2 ] ; then
    echo "usage: runMany <numBH> <numRad> <label>"
    exit
fi

imaxBH=$1
imaxRad=$2
label=$3

i=0

cp Cards/run_card.dat ../new_trident_Rad_new_cuts4_Takashi/Cards/

#for x in 01 02 03 04 05 06 07 08 09 10 ; do
for x in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20; do
    if [ $i -lt $imaxBH ]; then
        ./bin/generate_events 0 ${label}_BH_$x
    fi
    if [ $i -lt $imaxRad ]; then
        pushd ../new_trident_Rad_new_cuts4_Takashi/
        ./bin/generate_events 0 ${label}_Rad_$x
        popd    
    fi
    let i="$i+1"
done
